### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [mergesort/Anchorman#6] opened 2016-09-21 09:04 UTC
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by mergesort** [comment] 2016-09-21 18:55
Same here. I've tried rewriting this a few ways, but changes in NSLayoutAnchor, now being constrained across generics (NSLayoutXAxisAnchor, NSLayoutYAnchor, and NSLayoutDimension) have made it a bit tough. I have another approach that I've been thinking about, and I'm going to give it another shot in  the coming weeks, once some life things settle down.

**Comment by zhigang1992** [comment] 2016-09-22 19:04
Gave it a try, still a bit primitive.
But let me know what you think. 😄 

https://gist.github.com/zhigang1992/4247751d4e09c5884d9fd5abcd393ca7

**Comment by zhigang1992** [comment] 2016-09-22 19:05
Also here is a crazy version, properly not gonna be doing this, but still worth a try. :trollface: 

https://gist.github.com/zhigang1992/e353744e226615cb2ac458c97db24f87

**Comment by mergesort** [comment] 2016-09-22 22:40
@zhigang1992 I really appreciate the effort! Even having another way to think about it is helpful.

I think that I can take some inspiration from this implementation, but the issue is that the syntax doesn't resemble the old syntax very much. My goal is to rewrite it, and make it as close to compatible with the API layer of the original library.

**Comment by zhigang1992** [comment] 2016-09-23 12:18
@mergesort I actually start out implementing the sample API interface, but along the way I realize it's not just edges, it might be centers or width/height. That's when I renamed it to anchor.

😄

**Comment by mergesort** [comment] 2016-10-04 19:27
As of [release 1.2](https://github.com/mergesort/Anchorman/releases/tag/1.2), you can consider this done, so I'm going to close this out. 

Thanks @zhigang1992 for the help!

**Closed as completed by mergesort** 2016-10-04 19:27 UTC
